version: "3"
services:
  web:
    image: arieszhang/compose-demo:v1.0
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "8084:80"
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      # For windows containers
      - "E:\\Temp\\compose-demo\\redis:/data"
      # For linux containers
      # - "/home/docker/data:/data"
    command: redis-server --appendonly yes
    networks:
      - webnet

networks:
  webnet: